<h2>Наши продукты</h2>
<?php $currentPage  = $view->getParam('currentPage'); ?>
<?php $limit        = $view->getParam('limit'); ?>
<?php $orderType    = $view->getParam('orderType'); ?>
<?php $orderBy      = $view->getParam('orderBy'); ?>
<?php $products     = $view->getParam('products'); ?>
<?php $page_link    = $view->getParam('page_link'); ?>
<?php if(!empty($products)) :?>
    <table border="1px">
        <th>
            <?php if($orderType == 'asc') : ?>
                <a href='/product/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/id/ordertype/desc'>Id<?php if($orderBy == 'id') :?>&darr;<?php endif; ?></a>
            <?php else : ?>
                <a href='/product/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/id/ordertype/asc'>Id<?php if($orderBy == 'id') :?>&uarr;<?php endif; ?></a>
            <?php endif; ?>    
        </th>

        <th>
            <?php if($orderType == 'asc') : ?>
                <a href='/product/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/name/ordertype/desc'>Name<?php if($orderBy == 'name') :?>&darr;<?php endif; ?></a>
            <?php else : ?>
                <a href='/product/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/name/ordertype/asc'>Name<?php if($orderBy == 'name') :?>&uarr;<?php endif; ?></a>
            <?php endif; ?>
        </th>        
        <th>Picture</th>    
        <th>
            <?php if($orderType == 'asc') : ?>
                <a href='/product/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/price/ordertype/desc'>Price<?php if($orderBy == 'price') :?>&darr;<?php endif; ?></a>
            <?php else : ?>
                <a href='/product/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/price/ordertype/asc'>Price<?php if($orderBy == 'price') :?>&uarr;<?php endif; ?></a>
            <?php endif; ?>
        </th>    
        <th>
            <?php if($orderType == 'asc') : ?>
                <a href='/product/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/total/ordertype/desc'>Total<?php if($orderBy == 'total') :?>&darr;<?php endif; ?></a>
            <?php else : ?>
                <a href='/product/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/total/ordertype/asc'>Total<?php if($orderBy == 'total') :?>&uarr;<?php endif; ?></a>
            <?php endif; ?>
        </th>    

        <?php foreach($products as $product) : ?>
            <?php /** @var Model_Product $product*/ ?>
            <tr>
                <td><?php echo $product->id;?></td>
                <td><?php echo $product->name;?></td>
                <td><?php echo $product->img;?></td>
                <td><?php echo $product->price;?></td>
                <td><?php echo $product->total;?></td>
                <td><a href='/product/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/total/ordertype/desc'>Редактирование<?php if($orderBy == 'total') :?><?php endif; ?></a></td>
            </tr>
        <?php endforeach; ?>
    </table>  <br />

    <?php $countPages = ceil($view->getParam('countProducts') / $limit); ?>

        <!--Ссылка на первую страницу-->
        <a href='/product/index/page/<?php echo $currentPage = 1;?>/limit/<?php echo $limit;?>'>&lt;&lt;</a> ... 
        <?php $currentPage  = $view->getParam('currentPage'); ?>
        
        <!-- Выводим ссылку "Назад", если это не первая страница -->
        <?php if($currentPage != 1): ?>
            <a href="/product/index/page/<?php echo $currentPage - 1;?>/limit/<?php echo $limit;?>" >&lt;</a> ... <?php endif;?>
            
        <!-- Выводим предыдущие элементы -->
        <?php if($currentPage > $page_link + 1): ?>
        <?php for ($i = $currentPage - $page_link; $i < $currentPage; $i++) :?>
            <a href="/product/index/page/<?php echo $i;?>/limit/<?php echo $limit;?>/orderby/<?php echo $orderBy ?>/ordertype/<?php echo $orderType; ?>"><?php echo $i;?></a>&nbsp&nbsp
        <?php endfor; ?>
            <?php else : ?>
               <?php for ($i = 1; $i < $currentPage; $i++):?>
            <a href="/product/index/page/<?php echo $i;?>/limit/<?php echo $limit;?>/orderby/<?php echo $orderBy ?>/ordertype/<?php echo $orderType; ?>"><?php echo $i;?></a>&nbsp&nbsp
               <?php endfor; ?>
        <?php endif;?> 
            
        <!-- Выводим текущий элемент -->
        <?php echo $i;?>&nbsp&nbsp
        
        <!-- Выводим следующие элементы -->
        <?php if($currentPage + $page_link < $countPages): ?>
        <?php for ($i = $currentPage + 1; $i <= $currentPage + $page_link; $i++) :?>
            <a href="/product/index/page/<?php echo $i;?>/limit/<?php echo $limit;?>/orderby/<?php echo $orderBy ?>/ordertype/<?php echo $orderType; ?>"><?php echo $i;?></a>&nbsp&nbsp
        <?php endfor; ?>
            <?php else : ?>
               <?php for ($i = $currentPage + 1; $i <= $countPages; $i++):?>
            <a href="/product/index/page/<?php echo $i;?>/limit/<?php echo $limit;?>/orderby/<?php echo $orderBy ?>/ordertype/<?php echo $orderType; ?>"><?php echo $i;?></a>&nbsp&nbsp
               <?php endfor; ?>
        <?php endif;?> 
<?php endif; ?>

             <!-- Выводим ссылку вперёд, если это не последняя страница -->
        <?php if($currentPage != $countPages): ?>
            <a href="/product/index/page/<?php echo $currentPage + 1;?>/limit/<?php echo $limit;?>" >...&gt;</a> ... <?php endif;?>
            
             <!-- Ссылка на последнюю страницу -->
            <a href='/product/index/page/<?php echo $currentPage = $countPages ;?>/limit/<?php echo $limit;?>'>&gt;&gt;</;</a> 